theme: academic
title: Hannah Bailey
title_html: "<b>Hannah<span class=\"invisible\"> </span> Bailey</b>"

langs: ["en"]
encoding: UTF-8

# author
author: Hannah Bailey
email: hannah.bailey@oii.ox.ac.uk
shortbio: Hannah Bailey is a researcher at the Oxford Internet Institute at the University of Oxford
twitter_username: Hannah_LSBailey
github_username: hannahlsbailey


#nav_ext_links:
#  - name: Link 1
#    url: http://jupiterbroadcasting.com/
#  - name: Link 2
#    url: http://wallabag.org/
